Documentation MC-757
MD2Korg/mCerebrum-PhoneSensor pull request #8
Opened 2018-01-26 16:07 UTC by hippietilley

2018-01-26 19:28 UTC, twhnat requested changes
Looking good for a first pass

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java
> +     * TODO: Consider listing required permissions
Please add these as a list

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java
> +     * TODO: Consider listing required permissions
You can find these in the AndroidManifest.xml file

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java
> +                    /**
Remove comment

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java
> +                    /**TODO: Not sure what this does other than check permissions again...
The does keep asking for location service permissions

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/Constants.java
> +     */
Enumerate activities

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/ResponseCallback.java
> +/**
no empty comments

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/AmbientLight.java
>  public class AmbientLight extends PhoneSensorDataSource implements SensorEventListener{
This class should have a detailed comment

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java
>  class LocationFused extends PhoneSensorDataSource {
Class comment

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java
> +                                .setAlwaysShow(true)  //Reference: http://stackoverflow.com/questions/29824408/google-play-services-locationservices-api-new-option-never
Move this reference to the method javadoc

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/PhoneSensorDataSource.java
> +     * <code>EPSILON_NORMAL</code> is 2.0 by default
What does 2.0 mean?

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/geofence/GeoFenceData.java
> + *
...

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/geofence/GeoFenceLocationInfo.java
> + *
....

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/requirement/Requirement.java
> + *
...

2018-01-26 19:28 UTC, twhnat commented on phonesensor/src/main/java/org/md2k/phonesensor/requirement/Requirement.java
>  public class Requirement {
@monowar What is this and why is it here?  Can we delete it?

2018-01-31 17:32 UTC, twhnat commented
Review status: 0 of 38 files reviewed at latest revision, 51 unresolved discussions, some commit checks broke.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 383 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C7_qjH7-tyZL-F_kz:-L4C7_qjH7-tyZL-F_l-:bipy4zx) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L383)):*
> ```Java
> 
>     /**
>      * TODO: What is this looking for a response from??
> ```

@monowar What is the intended behavior of this method?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 412 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C7tUCjgg60l-wLy8P:-L4C7tUCjgg60l-wLy8Q:b1tqxs7) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L412)):*
> ```Java
>     void checkRequirement() {
>         Intent intent = new Intent(this, ActivityPermission.class);
>         startActivityForResult(intent, 1111);
> ```

What is the meaning of 1111?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 425 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C8Zd6BeDv9yNuc6xW:-L4C8Zd6BeDv9yNuc6xX:b1tqxs7) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L425)):*
> ```Java
> @Override
> public void onActivityResult(int requestCode, int resultCode, Intent data) {
>     if (requestCode == 1111) {
> ```

What is the meaning of 1111?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 447 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C8eksXgg5-BTRz1xi:-L4C8eksXgg5-BTRz1xj:b1fzyte) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L447)):*
> ```Java
>      * Sets the operation mode based on whether the intent has extras.
>      */
>     void readIntent() {
> ```

This code block needs better formatting (proper tabs).  

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java, line 81 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C8rmQzpqbFy_tSNHG:-L4C8rmQzpqbFy_tSNHH:b-kkdpf8) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java#L81)):*
> ```Java
>                 Intent myIntent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
>                 myIntent.setData(Uri.parse("package:" + getPackageName()));
>                 startActivityForResult(myIntent, 101);
> ```

What is 101?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java, line 127 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C9C8hwjSxU8T-RHxU:-L4C9546E3Hydmn9jgHh:bcz231r) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java#L127)):*
> ```Java
>             if (googleAPI.isUserResolvableError(result)) {
>                 googleAPI.getErrorDialog(ActivityPermission.this, result,
>                         9000, new DialogInterface.OnCancelListener() {
> ```

What is 9000?  This should appear in the main javadoc . I am seeing this multiple times.  Please make it a CONSTANT or read from an Enumeration.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/Constants.java, line 38 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CADmu9EFzqVvI-RHT:-L4CADmu9EFzqVvI-RHU:bl45jye) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/Constants.java#L38)):*
> ```Java
>  */
> public class Constants {
>     public static final String FILENAME_ASSET_METADATA = "meta_data.json";
> ```

Should this have a javadoc?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/Constants.java, line 39 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAGe_3heS4Jm4ka7U:-L4CAGe_3heS4Jm4ka7V:b-x28ptd) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/Constants.java#L39)):*
> ```Java
> public class Constants {
>     public static final String FILENAME_ASSET_METADATA = "meta_data.json";
>     private Constants() {
> ```

What is this?  Unneeded?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/Constants.java, line 42 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CABDUa7D-SfD80RYy:-L4CABDUa7D-SfD80RYz:bl45jye) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/Constants.java#L42)):*
> ```Java
>     }
> 
>     public static final String PACKAGE_NAME = "org.md2k.phonesensor";
> ```

Should this have a javadoc?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java, line 120 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAacin8iaOpAw7Y92:-L4CAacin8iaOpAw7Y93:b2jgvux) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java#L120)):*
> ```Java
>     }
> 
>     private static final long INTERVAL = 5000L;
> ```

What is this? 5 seconds?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java, line 403 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CArxnHBt9evzCstIW:-L4CArxnHBt9evzCstIX:b-365ray) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java#L403)):*
> ```Java
>                 switchPreference.setOnPreferenceClickListener(alertDialogFrequency(Gyroscope.frequencyOptions));
>                 break;
>             case (DataSourceType.AMBIENT_TEMPERATURE):
> ```

 @monowar Why was the code commented out here?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java, line 411 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAwM4-W3ppAe7yby2:-L4CAwM4-W3ppAe7yby3:b-365ray) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java#L411)):*
> ```Java
>                 switchPreference.setOnPreferenceClickListener(alertDialogFrequency(AmbientLight.frequencyOptions));
>                 break;
>             case (DataSourceType.PRESSURE):
> ```

 @monowar Why was the code commented out here?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java, line 413 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAx4z0_M1vUCG7TgR:-L4CAx5-9-oQTpEtTLun:b-365ray) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java#L413)):*
> ```Java
>             case (DataSourceType.PRESSURE):
>                 break;
>             case (DataSourceType.PROXIMITY):
> ```

 @monowar Why was the code commented out here?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettingsGeofence.java, line 90 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CBIh56BEjbLCM47OI:- [...]

2018-01-31 17:33 UTC, twhnat commented
Reviewed 2 of 37 files at r1, 36 of 36 files at r2.
Review status: all files reviewed at latest revision, 51 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8)*
<!-- Sent from Reviewable.io -->

2018-01-31 21:55 UTC, hippietilley commented
Review status: 19 of 38 files reviewed at latest revision, 52 unresolved discussions.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 412 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C7tUCjgg60l-wLy8P:-L4CgYP4Cc7NQjGpCdmS:b-65z3ow) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L412)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is the meaning of 1111?
</blockquote></details>

1111 is the result code associated with this check. Notation has been added.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java, line 425 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C8Zd6BeDv9yNuc6xW:-L4CgiBV32SMZld5rft6:b-fkp9bt) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityMain.java#L425)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is the meaning of 1111?
</blockquote></details>

1111 is the result code associated with checkRequirement(). I pulled it out as a constant.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java, line 205 at r1](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C6fqPT5he4EvqOb1t-r1-205:-L4CnV3V5q97Kkv6feJi:b-dtqk56) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/2b390bb3598151e4807861fd9b8dce30fb77358b/phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java#L205)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

Remove comment
</blockquote></details>

The reference has been moved into the javadoc. I left a "see reference" comment in it's place.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java, line 81 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C8rmQzpqbFy_tSNHG:-L4ChgGBopPcyFu-QgTb:b-xp3sdr) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java#L81)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is 101?
</blockquote></details>

It's the result code for checking overlay permissions. I pulled it out as a constant.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java, line 127 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C9C8hwjSxU8T-RHxU:-L4ClWUXuulSLCW2Y9iu:b-r84swg) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/ActivityPermission.java#L127)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is 9000?  This should appear in the main javadoc . I am seeing this multiple times.  Please make it a CONSTANT or read from an Enumeration.
</blockquote></details>

It's another request code. I pulled it out as a constant.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/Constants.java, line 39 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAGe_3heS4Jm4ka7U:-L4CoT8Z1ulHwPvshgT8:bkddwtt) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/Constants.java#L39)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is this?  Unneeded?
</blockquote></details>

It seems to be an empty constructor.... I'm pretty sure it's unneeded, but I don't want to maybe break anything without permission.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java, line 120 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAacin8iaOpAw7Y92:-L4CqTyrUKAwqkrO1aYy:b-leb5qm) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/PrefsFragmentSettings.java#L120)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is this? 5 seconds?
</blockquote></details>

Yes, it's the frequency for location updates.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Accelerometer.java, line 158 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CCGv9Wgh2t5jOk4FG:-L4CsLqMV6r3IFbvUfcR:b2cv46c) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Accelerometer.java#L158)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

16.0 should become SENSOR_DELAY_UI, repeat for all in this case statement
</blockquote></details>

Should I also refactor 1000.0 into a millisecond constant too?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/AmbientLight.java, line 53 at r1](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C6fqPT5he4EvqOb27-r1-53:-L4Cv_xpDIVD5RB-txIx:b4z1qd0) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/2b390bb3598151e4807861fd9b8dce30fb77358b/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/AmbientLight.java#L53)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

This class should have a detailed comment
</blockquote></details>

Added the default sampling rate. Any other information you think should be included?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Battery.java, line 92 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CCzHSKdGm-_6jlCdQ:-L4Cw_CpU0X9fNx6h1_o:b-fwpneu) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Battery.java#L92)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

Sampling rate?
</blockquote></details>

Do you want default sampling rate in the class javadoc or the constructor, or both?

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 83 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CDRWlbuivO6zSIX_c:-L4CyWVQKTluSVRO2CQf:bu1ex84) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L83)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

What is RADIUS?  Units?
</blockquote></details>

It's in meters and it's the radius of the geofence.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 273 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CDx40kjvdGEMAiFH-:-L4Cz6nVAuVl4Frnhl3d:bz5dfym) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L273)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

'abc' does not seem like the correct thing to put here.  I believe that TAG is generally used.
</blockquote></details>

TAG is generic. According to the android docs, it's used to determine the source of the log message. So maybe GEO would be more appropriate...

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 340 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CE3r [...]

2018-02-06 04:36 UTC, twhnat commented
Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks broke.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/Constants.java, line 39 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CAGe_3heS4Jm4ka7U:-L4dMPz57nhuWcARhZAp:by5l7yy) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/Constants.java#L39)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

It seems to be an empty constructor.... I'm pretty sure it's unneeded, but I don't want to maybe break anything without permission.
</blockquote></details>

Please keep all empty constructors for now.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Accelerometer.java, line 158 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CCGv9Wgh2t5jOk4FG:-L4dMofWbam4XnbamqV9:bwymhq5) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Accelerometer.java#L158)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

Should I also refactor 1000.0 into a millisecond constant too?
</blockquote></details>

Not necessary

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/AmbientLight.java, line 53 at r1](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4C6fqPT5he4EvqOb27-r1-53:-L4dN2lJmVI0Lk6Gf4x4:b7wl5ko) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/2b390bb3598151e4807861fd9b8dce30fb77358b/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/AmbientLight.java#L53)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

Added the default sampling rate. Any other information you think should be included?
</blockquote></details>

Not right now, I will need to see a javadoc of the project to be sure

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Battery.java, line 92 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CCzHSKdGm-_6jlCdQ:-L4dNLKj8sfF3WW2TdBK:bclt3ko) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/Battery.java#L92)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

Do you want default sampling rate in the class javadoc or the constructor, or both?
</blockquote></details>

Good point, lets just put it in the class doc

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 273 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CDx40kjvdGEMAiFH-:-L4dNkGfqnbjJ3As48uj:b-8hq0ma) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L273)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

TAG is generic. According to the android docs, it's used to determine the source of the log message. So maybe GEO would be more appropriate...
</blockquote></details>

Look at the other sensors for Log.d statements and let us replicate how they handle it

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 340 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CE3r8cPYNYxYli0qZ:-L4dO-aM5f06jPtSCsFE:b-8a7g1x) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L340)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

12 is an identifier. It allows PugNotification to know which notification to cancel.
</blockquote></details>

abstract out to a comment that has contextual meaning.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java, line 82 at r3](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4dOE1bvYDeCEtMF5tI:-L4dOE1bvYDeCEtMF5tJ:bb752ax) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/936b561ec64e2c4f4ed03b86a5d4c8b5d413fd6a/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java#L82)):*
> ```Java
>      *
>      * <p>
>      *     Deafault is 60,000 milliseconds (the number of milliseconds in a minute)
> ```

Typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8)*
<!-- Sent from Reviewable.io -->

2018-02-07 16:02 UTC, hippietilley commented
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks broke.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 273 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CDx40kjvdGEMAiFH-:-L4kzhZ2izrAz2IlrtcB:bg8vf8a) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L273)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

Look at the other sensors for Log.d statements and let us replicate how they handle it
</blockquote></details>

The only other sensor that uses LOG.d is stepCount and it's tag is also "abc". Maybe GEO for geofence and STEP for stepCount would be better.

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java, line 340 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CE3r8cPYNYxYli0qZ:-L4kyEzbWB2wbevV6S-9:b-7rl0kd) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/GeoFence.java#L340)):*
<details><summary><i>Previously, twhnat (Timothy Hnat) wrote…</i></summary><blockquote>

abstract out to a comment that has contextual meaning.
</blockquote></details>

done

---

*[phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java, line 189 at r2](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8#-L4CEbIQIqfG1hYbVIWR:-L4ky8CBbo9utHrv6VnD:b-hw4u9k) ([raw file](https://github.com/md2korg/mcerebrum-phonesensor/blob/4d0729ef133409139d2f045ffa9b28f22e077559/phonesensor/src/main/java/org/md2k/phonesensor/phone/sensors/LocationFused.java#L189)):*
<details><summary><i>Previously, hippietilley (Xavier Tilley) wrote…</i></summary><blockquote>

12 is an identifier. It allows PugNotification to know which notification to cancel.
</blockquote></details>

Extracted as a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8)*
<!-- Sent from Reviewable.io -->

2018-02-09 05:37 UTC, twhnat commented
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8)*
<!-- Sent from Reviewable.io -->

2018-02-14 19:07 UTC, twhnat commented
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/md2korg/mcerebrum-phonesensor/8)*
<!-- Sent from Reviewable.io -->

2018-02-14 19:09 UTC, twhnat approved these changes

2018-02-14 19:09 UTC, merged